### ISSUE TITLE
Update to PhotoSwipe 4.1.1

### ISSUE THREAD

**Issue by Jack12816** [skakri/photoswipe-rails#6]
Could you update this gem to the latest version of PhotoSwipe? :smiley: 

https://github.com/dimsemenov/PhotoSwipe/releases/tag/v4.1.1

**Comment by skakri** [comment]
I'm sorry, I somehow missed email of this issue. Pushed to rubygems.

**Comment by Jack12816** [comment]
Awesome! Thank you :)
